# Generated by Django 5.0.4 on 2024-05-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_to_disease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='person_to_disease',
            name='user',
        ),
        migrations.DeleteModel(
            name='disease',
        ),
        migrations.DeleteModel(
            name='person_to_disease',
        ),
    ]
