# Generated by Django 5.0.4 on 2024-06-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_disease_person_to_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_to_disease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='person_to_disease',
            name='user',
        ),
        migrations.DeleteModel(
            name='disease',
        ),
        migrations.DeleteModel(
            name='person_to_disease',
        ),
    ]
