# Generated by Django 5.0.4 on 2024-06-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_remove_person_to_disease_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='pfp',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
