# Generated by Django 5.0.4 on 2024-06-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_remove_user_profile_pfp_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='pfp',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
