# Generated by Django 5.0.4 on 2024-05-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_messages_reciever_messages_chatroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
